language: python
python: 3.6

script:
  - pytest tests/unit

install:
  - rm -rf .coverage
  - python setup.py develop
  - python -c "import nltk ; nltk.download('punkt')"
  - python -c "import nltk ; nltk.download('stopwords')"
  - pip install coveralls pytest pytest-cov
